fix: inline code break when pressing Enter followed by Backspace twice
toeverything/blocksuite pull request #1353
Opened 2023-02-24 05:48 UTC by zqran

close: #1319

2023-02-24 17:53 UTC, Himself65 requested changes

2023-02-24 17:53 UTC, Himself65 commented on packages/blocks/src/__internal__/rich-text/rich-text.ts
> +        // console.log(this.quill);
remove

2023-02-25 04:51 UTC, doodlewind approved these changes

2023-02-25 04:52 UTC, merged

2023-02-25 04:52 UTC, doodlewind commented
Good catch, thanks!