chore: improve drag handle in database
toeverything/blocksuite pull request #1757
Opened 2023-03-18 11:26 UTC by fundon

2023-03-21 12:54 UTC, fundon commented
> One thing I want to confirm is whether the following two visual effects need to be consistent?

If the database is empty, the width of drag handle line is equals database block' width, otherwise it equals to the specific block' width.

2023-04-02 01:39 UTC, fundon commented
@zqran 


https://user-images.githubusercontent.com/27926/229326372-21b601e1-3546-4428-a2e4-0fb76ed76dda.mov

2023-04-02 05:18 UTC, lawvs requested changes

2023-04-02 05:18 UTC, lawvs commented on packages/blocks/src/components/block-hub.ts
> +      }
I suggest adding some comments about drag details here for better understanding

2023-04-02 06:08 UTC, zqran commented
> @zqran Throws an exception when all rows are moved out of the database

Fixed.

2023-04-03 04:32 UTC, doodlewind approved these changes

2023-04-03 04:33 UTC, merged