fix: tooltip should be hidden when the submenu list is opened
toeverything/blocksuite pull request #1924
Opened 2023-04-02 09:59 UTC by PerfectPan

Close https://github.com/toeverything/blocksuite/issues/1845
I had two considerations in fixing this issue:
1. It seems that I can either create a new prop to control whether a tooltip should be displayed or just clear tooltip. I choose the latter because I think the value of tooltip can potentially represent whether it should be displayed. Just like the code written in file:
```ts
${tooltip
  ? html`<tool-tip inert role="tooltip" tip-position="top" arrow
      >${tooltip}</tool-tip
    >`
  : nothing}
```
2. I create a state to track the state of the popper so that I can request a render when the state changes reactively.

2023-04-03 09:08 UTC, alt1o requested changes

2023-04-03 09:08 UTC, alt1o commented on packages/blocks/src/page-block/edgeless/toolbar/brush-tool/brush-tool-button.ts
> +          : getTooltipWithShortcut('Pen', 'P')}
Prefer to use ```null``` or ```empty string```

2023-04-03 09:08 UTC, alt1o commented on packages/blocks/src/page-block/edgeless/toolbar/brush-tool/brush-tool-button.ts
> +        .testId=${'brush'}
It is recommended to use locatorEdgelessToolButton to locate the tool button, without the need to add a new testId.

2023-04-05 14:20 UTC, doodlewind approved these changes

2023-04-05 14:38 UTC, merged

2023-04-05 14:38 UTC, doodlewind commented
Landed, thanks!