refactor: remove virgo pure mode and add `VirgoInput`
toeverything/blocksuite pull request #2378
Opened 2023-05-01 09:26 UTC by Flrande

Close #2349

2023-05-01 12:46 UTC, zqran requested changes

2023-05-01 12:46 UTC, zqran commented on packages/blocks/src/components/virgo-input/virgo-input.ts
> +        throw 'The text exceeds the limit length.';
```suggestion
        throw new Error('The text exceeds the limit length.');
```

I think we should aways use this format.

2023-05-01 12:46 UTC, zqran commented on packages/blocks/src/components/virgo-input/virgo-input.ts
> +            this.undoManager.redo();
```suggestion
            this.redo();
```
This is more concise.

2023-05-02 00:46 UTC, zqran approved these changes

2023-05-02 01:16 UTC, doodlewind approved these changes

2023-05-02 01:16 UTC, merged