feat(edgeless): edgless element drag snap
toeverything/blocksuite pull request #2967
Opened 2023-06-02 08:02 UTC by regischen

It is the design draft of edgeless element snap.
there are two things necessarily to be viewd. @doodlewind 
1. the API of `EdgelessSnapManager` and how it can be used.
2. I add mechanism to allow renderer to render non-phaserElement.

2023-06-09 06:30 UTC, doodlewind commented on packages/blocks/src/page-block/edgeless/snap-manager.ts
> +          /** 左边对齐 */
Don't use Chinese comment

2023-06-09 07:23 UTC, regischen commented on packages/blocks/src/page-block/edgeless/snap-manager.ts
> +          /** 左边对齐 */
ookay, I will notice in the following

2023-06-09 09:29 UTC, doodlewind requested changes
1. Some trivial refactoring could be done with the help of GPT.
2. The newly added `Renderable` concept looks a bit arbitrary and is something that doesn't fit perfectly into our CRDT-driven system in phasor. I need to think about the best practice  here.

2023-06-13 04:50 UTC, doodlewind approved these changes
LGTM, thanks for adding this critical functionality!

2023-06-13 04:53 UTC, merged

2023-06-13 04:56 UTC, regischen commented
> LGTM, thanks for adding this critical functionality!
Also thanks for greatly improving quality of these codes!
now it fits more naturally into the project!

2023-06-13 04:56 UTC, regischen commented
> LGTM, thanks for adding this critical functionality!

Also thanks for greatly improving quality of these codes!
now it fits more naturally into the project!