handling backspace key press for cursor transition from paragraph to page title
toeverything/blocksuite pull request #3148
Opened 2023-06-17 15:28 UTC by zhengjitf

Fix #2976, about the delete action. (For forward-delete fixed by https://github.com/toeverything/blocksuite/pull/2552)

2023-06-18 15:49 UTC, doodlewind requested changes
Thanks for your contribution! But I think for the first paragraph block, we should not simply delete it in this case. Otherwise there will be no content inside the note container, which will make it unable to focus to the content area:

<img width="772" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/793a633b-9920-4e30-85d9-162a9091c5b9">

So as an alternative, I think simply focus the cursor to the end of the title (without deleting the first paragraph block) can be preferable. If you are open to further investigation, feel free to ask for help!

2023-06-19 02:51 UTC, zhengjitf commented
Added a judgment, if the paragraph has no next sibling, won't delete it, just clear text. Is this OK?


https://github.com/toeverything/blocksuite/assets/17249775/488e17b3-59b4-4e67-b1df-b1b8bd9c181e

2023-06-20 04:22 UTC, doodlewind approved these changes

2023-06-20 04:26 UTC, doodlewind reviewed
Sorry for the delay, thanks for your contribution! Also feel free to join our CN community at https://t.me/AffineDevCN if that helps :)

2023-06-20 04:26 UTC, merged