fix: package entry path after publish
toeverything/blocksuite pull request #381
Opened 2022-12-20 05:32 UTC by linonetwo

This bug happened after I upgrade from 0.3.0-alpha.7 to 0.3.0-alpha.13

This PR fix this when importing the package:

\`\`\`  
\[ERROR\] \[plugin vite:dep-scan\] Failed to resolve entry for package "@blocksuite/store". The package may have incorrect main/module/exports specified in its package.json.

   node\_modules/.pnpm/esbuild@0.16.10/node\_modules/esbuild/lib/main.js:1357:21:  
     1357 │         let result = await callback({  
\`\`\`

I tried modify package.json in node\_modules like this to fix it. But there may be better ways, like change this?

\`\`\`json  
 "publishConfig": {  
   "access": "public",  
   "main": "dist/index.js",  
   "types": "dist/index.d.ts",  
   "exports": {  
     "./src/\*": "./dist/\*.js",  
     ".": "./dist/index.js"  
   }  
 }  
\`\`\`

Seems you have changed the dist folder structure of store package, since 0.3.0-alpha.7 version

!\[截屏2022-12-20 13 19 47\](https://user-images.githubusercontent.com/3746270/208589782-9f38399a-1fe7-48a6-b5e5-130a5c3c772d.png)

2022-12-20 06:05 UTC, lawvs commented
The struct of the published package is changed. I think it is related to https://github.com/toeverything/blocksuite/pull/359

Can you have a look @Himself65 ?

```
# before
dist/
  index.js
  xxx.js

# after
dist/
  store/
    index.js
    xxx.js
  blocks/
    index.js
```

2022-12-20 06:14 UTC, lawvs requested changes
It's not a correct solution, please use 0.3.0-alpha.11 first, sorry for any inconvenience.

2022-12-20 07:57 UTC, closed without merging

2022-12-20 10:16 UTC, Himself65 commented
> The struct of the published package is changed. I think it is related to https://github.com/toeverything/blocksuite/pull/359
> 
> 
> 
> Can you have a look @Himself65 ?
> 
> 
> 
> ```
> 
> # before
> 
> dist/
> 
>   index.js
> 
>   xxx.js
> 
> 
> 
> # after
> 
> dist/
> 
>   store/
> 
>     index.js
> 
>     xxx.js
> 
>   blocks/
> 
>     index.js
> 
> ```

The reason is I set baseUrl to . and this will compile all related packages

2022-12-20 10:21 UTC, Himself65 commented
The correct solution is use vite to build the package

2022-12-21 15:35 UTC, lawvs commented
Fix in https://github.com/toeverything/blocksuite/commit/9c20074a16cf8e6e0f9a6f4f079a9ce13edfdfc0