refactor: make `rich-text` not based on model
toeverything/blocksuite pull request #4313
Opened 2023-08-23 08:37 UTC by Flrande

2023-08-23 14:05 UTC, zzj3720 commented
lgtm

2023-08-24 12:10 UTC, Saul-Mirone commented on packages/blocks/src/__internal__/rich-text/keymap/container.ts
> +    ' ': ctx => {
You can also use `Space`

2023-08-24 12:12 UTC, Saul-Mirone approved these changes
Great work!

2023-08-24 12:17 UTC, Saul-Mirone requested changes
Seems the behavior of `ArrowUp` and `ArrowDown` is not right in multi line rich text

2023-08-25 06:42 UTC, Saul-Mirone approved these changes

2023-08-25 07:33 UTC, Flrande commented
It will be merged after AFFiNE stable version released.

2023-08-25 11:33 UTC, merged