fix: image filename in card view
toeverything/blocksuite pull request #4583
Opened 2023-09-04 20:05 UTC by adityash1

Changes
-  shows image filename when dragged and dropped
-	And when uploaded via slash menu option

Fixes https://github.com/toeverything/AFFiNE/issues/4111

2023-09-05 09:45 UTC, lawvs requested changes
Thanks for your enthusiasm! However, The image block does not include the name property by design.

placing all miscellaneous data into a block scheme is not a good idea for several reasons:

- It will make type-checking unreliable. The growing amount of empty data will affect the development experience.
- They are mostly useless in most scenarios.
- It can also cause unexpected privacy leaks.

So we only save temporary data in memory. (If you refresh the page, the data carried over from the previous block will be lost.)

2023-09-05 17:41 UTC, adityash1 commented
> Thanks for your enthusiasm! However, The image block does not include the name property by design.
> 
> placing all miscellaneous data into a block scheme is not a good idea for several reasons:
> 
> * It will make type-checking unreliable. The growing amount of empty data will affect the development experience.
> * They are mostly useless in most scenarios.
> * It can also cause unexpected privacy leaks.
> 
> So we only save temporary data in memory. (If you refresh the page, the data carried over from the previous block will be lost.)

Makes sense.  It was using blob to get the filename. And as I know, blobs doesn't contain file names. What should be my other approach here ? Can you explain ?

2023-09-06 04:47 UTC, lawvs commented
> Makes sense. It was using blob to get the filename. And as I know, blobs doesn't contain file names. What should be my other approach here ? Can you explain ?

Yes, It's a bug. I'll add commits to your pull request that use a default name when no name is available in `attachmentConvertData`.

2023-09-07 09:26 UTC, lawvs approved these changes

2023-09-07 09:27 UTC, merged