feat: add surface sync block
toeverything/blocksuite pull request #5013
Opened 2023-10-13 05:26 UTC by doouding

**Change**
- support edgeless content in page mode

2023-10-17 13:22 UTC, doouding commented
I just updated the design doc. Feel free to post any comments. @doodlewind

2023-10-19 04:18 UTC, doodlewind reviewed
> The role of the `affine:surface-ref` is set to be hub, cause the content block cannot be the children of the root block. But the hub seems a little inappropriate.

@Saul-Mirone do you think we can break the previous assumption? In this case, `affine:page` could have both `affine:note` or `affine:surface-ref` as its direct children.

2023-10-27 12:47 UTC, doodlewind commented on packages/lit/src/utils/range-synchronizer.ts
> +        element.model.flavour === 'affine:surface-ref',
I think it's anti-pattern to hard-code `affine` related logic in the lit package. @Saul-Mirone any advice?

2023-10-31 02:34 UTC, Saul-Mirone commented on packages/lit/src/element/block-element.ts
> +  calculatePath = () => {
Why you need to expose this method?

2023-10-31 02:38 UTC, Saul-Mirone commented on packages/lit/src/utils/range-synchronizer.ts
> +        element.model.flavour === 'affine:surface-ref',
We shouldn't sync this block for native selection. Consider handle the edge case in `Delete` keymap.

2023-10-31 02:38 UTC, Saul-Mirone requested changes
We shouldn't hard code logic in lit and std package.

2023-10-31 06:38 UTC, Saul-Mirone approved these changes

2023-10-31 06:38 UTC, Saul-Mirone commented
It's okay to refactor later.

2023-10-31 07:02 UTC, doouding commented
FIXME comment has been added.

2023-10-31 08:24 UTC, merged

2023-10-31 08:24 UTC, doodlewind commented
Thanks for the feat, looking forward to the upcoming housekeeping updates!

2023-11-12 09:08 UTC, doouding commented
I will add some tests later on.