feat(edgeless): note upgrade
toeverything/blocksuite pull request #5337
Opened 2023-11-15 08:10 UTC by regischen

close #5283 
close #5234

2023-11-17 21:09 UTC, doodlewind commented on packages/blocks/src/page-block/edgeless/components/panel/note-shadow-panel.ts
> +import { NOTE_SHADOWS } from '../../../../note-block/note-model.js';
Don't cross referencing blocks, add const in common modules instead.

2023-11-17 21:10 UTC, doodlewind commented on packages/blocks/src/page-block/edgeless/components/panel/note-shadow-panel.ts
> +const TOOTIPS = [
Typo

2023-11-17 21:13 UTC, doodlewind commented on packages/blocks/src/page-block/edgeless/components/utils.ts
> +  clickAway = true
The mixing of `boolean` and `Disposable` typing is unacceptable.

2023-11-17 21:15 UTC, doodlewind commented on packages/blocks/src/note-block/note-model.ts
> +        shadowStyle: NOTE_SHADOWS[1],
`shadowStyle` -> `shadowType`

2023-11-17 21:17 UTC, doodlewind commented on tests/edgeless/note.spec.ts
> +  if (box === null) throw new Error();
Why not `assertExists`?

2023-11-17 21:21 UTC, doodlewind commented on tests/basic.spec.ts
> +    prop:edgeless={
This significantly bloats almost all test cases, which is very much a code smell. @Saul-Mirone any idea avoiding the duplicate here?

2023-11-17 21:32 UTC, doodlewind requested changes
Thank you for your contribution to the project. I appreciate the effort you've put into this. However, there are some concerns regarding the handling of potential technical debt that we need to address. It's important for the health and sustainability of the project that we proactively discuss and manage technical debt. I recommend we have a more thorough discussion about these aspects before proceeding to the code review stage. This will help us ensure the high quality and maintainability of our codebase. Let's work together to find the best approach to tackle these challenges. Your continued dedication and improvement are vital to our project's success.

(Generated from https://chat.openai.com/share/2565741f-0de3-4da9-a037-07accf96ddc4)

2023-11-18 04:19 UTC, regischen commented
> Thank you for your contribution to the project. I appreciate the effort you've put into this. However, there are some concerns regarding the handling of potential technical debt that we need to address. It's important for the health and sustainability of the project that we proactively discuss and manage technical debt. I recommend we have a more thorough discussion about these aspects before proceeding to the code review stage. This will help us ensure the high quality and maintainability of our codebase. Let's work together to find the best approach to tackle these challenges. Your continued dedication and improvement are vital to our project's success.

Thank you for your acknowledgment. Indeed, I should be more proactive in identifying issues that are worth discussing before the code review stage. This is to ensure the high quality and maintainability of our codebase.

2023-11-21 10:53 UTC, Svaney-ssman requested changes
Please hide the styles buttons when note[ in hidden mode](https://www.figma.com/file/ry2HHWu5XafpuXBD2XOvKd/%F0%9F%9B%96-2023.S4?type=design&node-id=587-21109&mode=design&t=gL09M2r3oZUR1TqM-4)
<img width="468" alt="image" src="https://github.com/toeverything/blocksuite/assets/110808979/ec38358a-da1b-4b0d-9c5d-5b8df8c36995">

2023-11-23 02:25 UTC, doodlewind approved these changes
About 1000 lines added in this PR relates to the default props of note block. We should mitigate this in test infra afterwards.

2023-11-23 05:46 UTC, Svaney-ssman approved these changes
good job👏

2023-11-23 05:46 UTC, merged