fix: enter in title move cursor
toeverything/blocksuite pull request #5962
Opened 2024-01-11 08:32 UTC by regischen

close #5960

2024-01-11 10:49 UTC, AyushAgrawal-A2 commented
@regischen 
can we add `this.host.event.activate();` inside the `asyncFocusRichText` function... it will solve other sch scenarios as well as editor should always be active when focus text is called

2024-01-11 11:18 UTC, doodlewind requested changes

2024-01-11 11:18 UTC, doodlewind commented on tests/hotkey.spec.ts
> +  await page.pause();
Remove this line.

2024-01-11 12:08 UTC, doodlewind approved these changes

2024-01-12 01:27 UTC, doodlewind commented
> @regischen 
> 
> can we add `this.host.event.activate();` inside the `asyncFocusRichText` function... it will solve other such scenarios as well, as editor should always be active when focus text is called

@regischen PTAL

2024-01-12 02:13 UTC, regischen commented
> @regischen can we add `this.host.event.activate();` inside the `asyncFocusRichText` function... it will solve other such scenarios as well, as editor should always be active when focus text is called

I'm not sure if this is best approach. \cc @Saul-Mirone

2024-01-12 02:13 UTC, merged