refactor: no longer manually control the activation status of the event dispatcher
toeverything/blocksuite pull request #6316
Opened 2024-02-28 06:12 UTC by Flrande

2024-02-28 06:13 UTC, doodlewind approved these changes

2024-02-29 02:13 UTC, Saul-Mirone requested changes

2024-02-29 02:13 UTC, Saul-Mirone commented on packages/blocks/src/root-block/edgeless/edgeless-keyboard.ts
> +  bindEdgelessHotKey(keymap: Record<string, UIEventHandler>) {
This seems not right. We shouldn't add specific implementation for edgeless mode of a common feature.

2024-03-01 03:11 UTC, Saul-Mirone approved these changes

2024-03-01 03:12 UTC, merged