fix(edgeless): drag note to merge after a list item
toeverything/blocksuite pull request #6461
Opened 2024-03-12 08:48 UTC by doouding

Closes: [BS-56](https://linear.app/affine-design/issue/BS-56/白板上，note-合并的功能坏了)

2024-03-12 09:51 UTC, doouding commented
> Can we add a test for this case?

Got it.

2024-03-12 10:02 UTC, donteatfriedrice approved these changes

2024-03-12 10:24 UTC, Saul-Mirone requested changes
Wait for test case

2024-03-12 21:02 UTC, doodlewind approved these changes

2024-03-13 05:15 UTC, Saul-Mirone approved these changes

2024-03-13 05:17 UTC, merged