fix(edgeless): dropout embed synced doc block should fit height
toeverything/blocksuite pull request #6463
Opened 2024-03-12 09:39 UTC by donteatfriedrice

To fix [AFF-613](https://linear.app/affine-design/issue/AFF-613/dropped-embedded-sync-doc-in-edgeless-doesnt-fit-in-height)

https://github.com/toeverything/blocksuite/assets/99816898/ec81c5b1-d9e6-4d7f-8e64-be52ec3e38e9

2024-03-12 09:40 UTC, Saul-Mirone commented
Great! Can we add some tests for this case?

2024-03-12 09:43 UTC, donteatfriedrice commented
> Great! Can we add some tests for this case?

Sure, I will add some tests for embed synced doc.

2024-03-12 10:24 UTC, Saul-Mirone requested changes
Wait for test case

2024-03-13 05:15 UTC, Saul-Mirone approved these changes

2024-03-13 05:50 UTC, merged