feat(edgeless): note block supports auto complete panel
toeverything/blocksuite pull request #6591
Opened 2024-03-27 09:24 UTC by fundon

2024-03-27 09:24 UTC, fundon commented
* **#6591** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/6591?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @fundon and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-03-28 07:30 UTC, fundon commented on packages/blocks/src/root-block/edgeless/components/auto-complete/edgeless-auto-complete.ts
> +    let strokeColor = '--affine-palette-line-grey';
`--affine-palette-line-grey`  `--affine-tag-gray`

Can we standardize the naming of these?

2024-03-28 07:39 UTC, hwangdev97 commented
if not matched, i think we need use grey/gray color, not black 🤔

2024-03-28 10:22 UTC, donteatfriedrice commented
> if not matched, i think we need use grey/gray color, not black 🤔

Maybe we not inherit the width and height ratio of note? The shape looks a bit weird 🤔.

2024-03-29 02:11 UTC, fundon commented
> Maybe we not inherit the width and height ratio of note? The shape looks a bit weird 🤔.

Yes, the width and height need some adjustment.

2024-03-29 02:17 UTC, Saul-Mirone requested changes
Please add tests.

2024-03-31 09:59 UTC, Saul-Mirone approved these changes

2024-03-31 10:08 UTC, merged