fix(edgeless): soft enter removes extra character
toeverything/blocksuite pull request #6691
Opened 2024-04-04 07:32 UTC by golok727

2024-04-04 10:21 UTC, Flrande requested changes

2024-04-04 10:21 UTC, Flrande commented on packages/blocks/src/database-block/common/columns/rich-text/cell-renderer.ts
> +      text.replace(inlineRange.index, 0, '\n');
The situation in the video should have a length of 0, so it may not be the source of the error.

2024-04-04 10:39 UTC, golok727 commented
> How to reproduce it?
> 
>  CleanShot.2024-04-04.at.18.18.54.mp4

It is not working in Chrome. Tested it in Edge and it is working 

https://github.com/toeverything/blocksuite/assets/123532141/7caec720-94bf-43d4-a668-aad2b417ddcd

2024-04-05 06:38 UTC, Flrande approved these changes

2024-04-05 06:38 UTC, merged