fix(edgeless): add a paragraph block when clicking on empty space on the note block
toeverything/blocksuite pull request #6870
Opened 2024-04-24 09:55 UTC by golok727

close https://github.com/toeverything/blocksuite/issues/6631

2024-04-24 10:17 UTC, donteatfriedrice requested changes
In this case, when the last block is a non-text block, a paragraph block will always be added at the bottom. The logic here should be to focus on the nearest text block first when clicking. If the nearest block is not text block, and the last block is not a text block, then add an empty block

2024-04-24 10:17 UTC, donteatfriedrice commented on packages/blocks/src/root-block/edgeless/components/block-portal/note/edgeless-note.ts
> +      matchFlavours(last, [
Can be changed to check whether it is a paragraph or a list

```
!matchFlavours(parent, ['affine:paragraph', 'affine:list'])
```

2024-04-24 10:17 UTC, donteatfriedrice commented on packages/blocks/src/root-block/edgeless/components/block-portal/note/edgeless-note.ts
> +    // add an empty paragraph
In this case, when the last block is a non-text block, a paragraph block will always be added at the bottom. The logic here should be to focus on the nearest text block first when clicking. If the nearest block is not text block, and the last block is not a text block, then add an empty block

2024-04-24 10:43 UTC, golok727 commented
>when the last block is a non-text block, a paragraph block will always be added at the bottom. 

When I tested this, I found that a paragraph block wasn't added at the bottom as described when adding a non-text. We need to click on the empty area in the doc to add a new text block. 

https://github.com/toeverything/blocksuite/assets/123532141/747f81bd-e7b9-4ad9-a709-cc9d9aebae2d

2024-04-24 10:52 UTC, donteatfriedrice commented
> >when the last block is a non-text block, a paragraph block will always be added at the bottom. 
> 
> 
> 
> When I tested this, I found that a paragraph block wasn't added at the bottom as described when adding a non-text. We need to click on the empty area in the doc to add a new text block. 
> 
> 
> 
> https://github.com/toeverything/blocksuite/assets/123532141/747f81bd-e7b9-4ad9-a709-cc9d9aebae2d
> 
> 
> 
> 

You can add some paragraph blocks before the table, and click at the top or left or right near the paragraph blocks, in this case, should focus on the paragraph first like in doc mode. In the video you uploaded, there are no text blocks before table,

2024-04-25 03:50 UTC, donteatfriedrice commented
> @donteatfriedrice How is this behavior? I think we should consider adding a + button like in notion beside the drag handle
> 
>  Thing2.mp4

Looks great! Thanks! Could you add tests for it ?

2024-04-25 03:51 UTC, donteatfriedrice approved these changes

2024-04-25 04:06 UTC, merged

2024-04-25 04:33 UTC, golok727 commented
> > @donteatfriedrice How is this behavior? I think we should consider adding a + button like in notion beside the drag handle
> > Thing2.mp4
> 
> Looks great! Thanks! Could you add tests for it ?

Sure!