feat(sync): add blob engine
toeverything/blocksuite pull request #6937
Opened 2024-04-30 11:15 UTC by Flrande

2024-05-01 15:28 UTC, doodlewind reviewed
How does this close #6294? I haven't found implementation for uploading image blobs to remote server endpoints yet.

Will also better to add the migration guide. For example, as downstream user, when syncing blobs to SQLite with legacy `BlobStorage` API (https://github.com/toeverything/blocksuite/blob/master/examples/react-sqlite/src/editor/provider/provider.ts#L17) , the migrated implementation should be hinted.

2024-05-01 15:38 UTC, Flrande commented
> How does this close #6294? I haven't found implementation for uploading image blobs to remote server endpoints yet.

This depends on the storage service used; perhaps we can write an example based on R2 or S3.

> Would also be better to add migration guide, aka the comparison between the new API surface and the implementation based on the legacy `BlobStorage`. This is needed for bumping downstream (e.g. https://github.com/toeverything/blocksuite/blob/master/examples/react-sqlite/src/editor/provider/provider.ts#L17)

I will update the migration document, and after merging, I will migrate the old implementation in the example.

2024-05-01 22:38 UTC, fourdim approved these changes
LGTM, but please wait for other reviewers.

2024-05-01 22:38 UTC, fourdim commented on packages/framework/sync/src/blob/engine.ts
> +              await shadow.set(key, data);
Consider log the error if data does not exist.

2024-05-01 22:38 UTC, fourdim commented on packages/framework/sync/src/blob/engine.ts
> +            await this.main.set(key, data);
Same here.

2024-05-02 07:22 UTC, Flrande commented
Considering the migration cost, I will merge this PR when AFFiNE releases 0.14. cc @pengx17 @EYHN

2024-05-06 06:43 UTC, EYHN approved these changes

2024-05-13 04:13 UTC, Saul-Mirone requested changes

2024-05-13 04:13 UTC, Saul-Mirone commented on packages/framework/sync/src/blob/engine.ts
> +export class BlobEngine {
Need unit test for this feature.

2024-05-23 08:38 UTC, Saul-Mirone approved these changes

2024-05-24 06:53 UTC, merged