feat(std): add execCommand to CommandManager
toeverything/blocksuite pull request #7090
Opened 2024-05-17 12:13 UTC by doouding

2024-05-17 12:13 UTC, doouding commented
* **#7090** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/7090?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @doouding and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-05-17 15:42 UTC, Saul-Mirone approved these changes

2024-05-17 15:47 UTC, Saul-Mirone requested changes
Could you please add som unit tests?

2024-05-20 01:54 UTC, doouding commented
I've added some tests.

2024-05-21 07:41 UTC, Saul-Mirone approved these changes

2024-05-21 07:42 UTC, merged