feat(blocks): embed html fullscreen toolbar
toeverything/blocksuite pull request #7138
Opened 2024-05-25 09:06 UTC by golok727

2024-05-25 09:06 UTC, golok727 commented
* **#7138** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/7138?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @golok727 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-05-26 18:12 UTC, fundon commented on packages/blocks/src/embed-html-block/components/fullscreen-toolbar.ts
> +        <div class="left">
May not need left or right to wrap buttons

2024-05-26 18:20 UTC, fundon requested changes

2024-05-26 18:20 UTC, fundon commented on packages/blocks/src/embed-html-block/styles.ts
> +    display: none;
Maybe `visibility: visible` will be better.

2024-05-26 18:20 UTC, fundon commented on packages/blocks/src/embed-html-block/components/fullscreen-toolbar.ts
> +      user-select: none;
It's not need here.

2024-05-26 18:20 UTC, fundon commented on packages/blocks/src/embed-html-block/components/fullscreen-toolbar.ts
> +      height: 24px;
icon-button has `width` and `height` properties.

2024-05-27 02:09 UTC, fundon approved these changes

2024-05-27 04:36 UTC, doodlewind approved these changes
Thanks for the feat!

2024-05-27 04:36 UTC, merged