refactor: use chat context
toeverything/blocksuite pull request #7162
Opened 2024-05-28 14:03 UTC by regischen

2024-05-28 16:36 UTC, Flrande requested changes

2024-05-28 16:36 UTC, Flrande commented on packages/presets/src/ai/chat-panel/actions/copy-more.ts
> +      console.log(stream);
remove it

2024-05-28 16:36 UTC, Flrande commented on packages/presets/src/ai/chat-panel/actions/copy-more.ts
> +        console.log('success');
same

2024-05-28 16:36 UTC, Flrande commented on packages/presets/src/ai/chat-panel/chat-cards.ts
> +export class ChatCards extends WithDisposable(LitElement) {}
What is this component used for?

2024-05-30 02:22 UTC, Saul-Mirone approved these changes

2024-05-30 04:04 UTC, Flrande approved these changes

2024-05-30 04:13 UTC, merged