chore(blocks): refine linked doc toolbar
toeverything/blocksuite pull request #7483
Opened 2024-07-03 05:47 UTC by fundon

Closes: [BS-584](https://linear.app/affine-design/issue/BS-584/linked-doc-toolbar)

2024-07-03 05:48 UTC, fundon commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/7483?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#7483** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/7483?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#7479** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/7479?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#7475** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/7475?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @fundon and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-04 03:57 UTC, Saul-Mirone requested changes

2024-07-04 03:57 UTC, Saul-Mirone commented on tests/edgeless/linked-doc.spec.ts
> -    await triggerComponentToolbarAction(page, 'linkedDocInfo');
If you want to remove these tests, you should add new one to protect your feature.

2024-07-04 09:33 UTC, Svaney-ssman reviewed
UI Issues:
1. both these two button status are hover, the default display should not have background color
![CleanShot 2024-07-04 at 17 27 21@2x](https://github.com/toeverything/blocksuite/assets/110808979/223c1d76-f3be-40fe-b20b-d9af11d9470e)

2. the font wight of menu is incorrect
![CleanShot 2024-07-04 at 17 30 24@2x](https://github.com/toeverything/blocksuite/assets/110808979/098aa62c-c0d2-4669-b169-6fb013451554)
![CleanShot 2024-07-04 at 17 31 10@2x](https://github.com/toeverything/blocksuite/assets/110808979/748f78a0-a500-4965-966e-098b205e3390)
![CleanShot 2024-07-04 at 17 33 07@2x](https://github.com/toeverything/blocksuite/assets/110808979/56d1e5f6-a0e3-470f-8095-1cb035efecce)

3. the reload button is missing

2024-07-05 04:45 UTC, Saul-Mirone approved these changes
LGTM

2024-07-10 02:57 UTC, Saul-Mirone reviewed
CI fails need to be fixed.

2024-07-10 03:18 UTC, fundon commented
> CI fails need to be fixed.

Maybe it will be better to check it in https://github.com/toeverything/blocksuite/pull/7520.

2024-07-10 03:20 UTC, Saul-Mirone commented
> > CI fails need to be fixed.
> 
> Maybe it will be better to check it in #7520.

In graphite you need to make sure every pr pass the ci check.

2024-07-10 06:59 UTC, doodlewind approved these changes

2024-07-10 08:09 UTC, merged