feat: add ai chat block
toeverything/blocksuite pull request #7577
Opened 2024-07-15 07:06 UTC by donteatfriedrice

2024-07-15 11:57 UTC, Saul-Mirone commented on packages/presets/src/blocks/ai-chat-block/ai-chat-block.ts
> +    const messages = this._deserializeChatMessages(this.model.messages).slice(
Recommend to use `this.model.messages$.value` to let lit subscribe the prop changes.

2024-07-16 01:50 UTC, doouding commented
LGTM

2024-07-16 06:29 UTC, Saul-Mirone commented on packages/presets/src/blocks/ai-chat-block/ai-chat-block.ts
> +  private _deserializeChatMessages = (messages: string) => {
```suggestion
  private _deserializeChatMessages = (messages: string) => {
  private _deserializedChatMessaged = computed(() => {
```

2024-07-16 06:30 UTC, Saul-Mirone commented on packages/presets/src/blocks/ai-chat-block/ai-chat-block.ts
> +    const result = ChatMessagesSchema.safeParse(JSON.parse(messages));
```suggestion
    const result = ChatMessagesSchema.safeParse(JSON.parse(this.model.messages$.value));
```

2024-07-16 06:30 UTC, Saul-Mirone commented on packages/presets/src/blocks/ai-chat-block/ai-chat-block.ts
> +  };
```suggestion
  });
```

2024-07-16 06:32 UTC, Saul-Mirone commented on packages/presets/src/blocks/ai-chat-block/ai-chat-block.ts
> +    const messages = this._deserializeChatMessages(
```suggestion
    const messages = this._deserializedChatMessaged.value.slice(-2);
```

2024-07-16 06:33 UTC, Saul-Mirone commented on packages/presets/src/blocks/ai-chat-block/ai-chat-block.ts
> +    ).slice(-2);
```suggestion
    const messages = this._deserializedChatMessaged.value.slice(-2);
```

2024-07-16 06:35 UTC, Saul-Mirone requested changes

2024-07-16 06:35 UTC, Saul-Mirone commented on packages/presets/src/blocks/ai-chat-block/ai-chat-block.ts
> +  };
```suggestion
  private _deserializeChatMessages = computed(() => {
    const messages = this.model.messages$.value
    try {
      const result = ChatMessagesSchema.safeParse(JSON.parse(messages));
      if (result.success) {
        return result.data;
      } else {
        return [];
      }
    } catch {
      return [];
    }
  };
```

2024-07-16 07:06 UTC, Saul-Mirone approved these changes

2024-07-16 07:23 UTC, merged