fix: edgeless text can not add max width
toeverything/blocksuite pull request #7686
Opened 2024-07-18 10:50 UTC by Flrande

Close BS-887

2024-07-18 11:10 UTC, doouding requested changes

2024-07-18 11:10 UTC, doouding commented on packages/framework/block-std/src/view/element/edgeless-block-element.ts
> +    if (y) this.style.top = `${y}px`;
x and y might be zero.

2024-07-19 11:39 UTC, doouding approved these changes

2024-07-19 13:42 UTC, Saul-Mirone approved these changes

2024-07-19 14:01 UTC, merged