refactor(presets): use customElement decorator
toeverything/blocksuite pull request #7700
Opened 2024-07-21 07:34 UTC by L-Sun

2024-07-21 07:34 UTC, L-Sun commented
* **#7700** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/7700?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @L-Sun and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-07-22 02:30 UTC, Saul-Mirone requested changes
Please also remove the `assertExists` in the logic.

2024-07-22 02:30 UTC, Saul-Mirone commented on packages/presets/src/fragments/frame-panel/card/frame-card-title-editor.ts
>  import { assertExists } from '@blocksuite/global/utils';
Please remove this `assertExists` in this file.

2024-07-22 02:30 UTC, Saul-Mirone commented on packages/presets/src/fragments/outline-panel/body/outline-panel-body.ts
> +import { DisposableGroup, assertExists } from '@blocksuite/global/utils';
Please remove this assertExists in this file.

2024-07-22 02:55 UTC, L-Sun commented
> Please also remove the `assertExists` in the logic.

I have remove `assertExists`, please check.

2024-07-23 07:24 UTC, Saul-Mirone approved these changes

2024-07-23 12:44 UTC, merged