chore: add editor mode related service on doc mode service
toeverything/blocksuite pull request #8110
Opened 2024-09-02 03:20 UTC by donteatfriedrice

2024-09-02 03:20 UTC, donteatfriedrice commented
* **#8110** <a href="https://app.graphite.dev/github/pr/toeverything/blocksuite/8110?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @donteatfriedrice and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-02 11:23 UTC, Saul-Mirone commented on packages/affine/shared/src/services/doc-mode-service.ts
> +  setPrimaryMode: (mode: DocMode, docId?: string) => void;
Let's also remove the `DocMode` enum and use pure string literal type (`page` | `edgeless`) instead.

2024-09-02 11:25 UTC, Saul-Mirone commented on packages/blocks/src/root-block/page/page-root-service.ts
> +  override readonly mode = DocMode.Page;
`BlockService` will be deprecated soon, we shouldn't add new logic on it.

2024-09-02 14:02 UTC, Saul-Mirone commented
This API is a little confusing for block developers. For example, what should I do if I want to check current editor mode?

2024-09-02 14:02 UTC, Saul-Mirone requested changes
Let's optimize the API

2024-09-03 09:21 UTC, donteatfriedrice commented
> Let's optimize the API

Originally, I thought of adding mode to the root service so that when developers want to get the mode, they can do so through rootService.mode. However, since the block service is about to be deprecated, this approach might not be suitable.

Do you have any suggestions regarding the following two points:

1. A suitable location to place the mode for easy user access?
2. API design for the doc mode service.

2024-09-03 10:19 UTC, doodlewind approved these changes

2024-09-04 09:53 UTC, Saul-Mirone commented on packages/affine/shared/src/services/doc-mode-service.ts
> +  setPrimaryMode: (mode: DocMode, docId: string) => void;
Please add some comments here to explain when to use primary mode and when to use editor mode.

2024-09-04 09:56 UTC, Saul-Mirone approved these changes
LGTM

2024-09-04 12:00 UTC, merged