refactor(inline): range sync
toeverything/blocksuite pull request #8368
Opened 2024-09-15 06:27 UTC by Flrande

2024-09-18 13:32 UTC, doodlewind reviewed
Wondering are there some RFCs or descriptions about the refactoring?

2024-09-18 14:49 UTC, Flrande commented
> Wondering are there some RFCs or descriptions about the refactoring?

No, because this PR did not cause many API changes; it mainly focuses on optimizing the existing code.

2024-09-19 10:16 UTC, Saul-Mirone requested changes
Waiting for resolving IME issues.

2024-09-20 00:54 UTC, Saul-Mirone commented on packages/framework/inline/src/services/render.ts
> +    delete (rootElement as any)['_$litPart$'];
Need to add a comment to explain what is this.

2024-09-20 00:56 UTC, Saul-Mirone commented on packages/framework/block-std/src/range/range-binding.ts
> +      delete (this.host.renderRoot as any)['_$litPart$'];
Same here

2024-09-20 00:57 UTC, Saul-Mirone approved these changes

2024-09-20 06:18 UTC, merged