feat(blocks): add hotkey for richtext
toeverything/blocksuite pull request #992
Opened 2023-02-04 08:44 UTC by Flrande

2023-02-04 10:13 UTC, doodlewind commented
When can we have test suite landed for Virgo? I would consider current stage a bit risky if we keep adding notable features without test cases.

2023-02-04 10:16 UTC, Flrande commented
Do you mean the test for basic style of virgo?

2023-02-04 10:20 UTC, Flrande commented
Actually, this pr has nothing to do with virgo. I add them just because Alex asked me to do that because he was unfamiliar with virgo api. What virgo will do next is support more accurate point and I will add test before develop it.

2023-02-04 10:29 UTC, doodlewind commented
> Actually, this pr has nothing to do with virgo. I add them just because Alex asked me to do that because he was unfamiliar with virgo api. What virgo will do next is support more accurate point and I will add test before develop it.

Got it, hope to see it happen soon!

2023-02-04 10:29 UTC, doodlewind approved these changes

2023-02-04 21:18 UTC, Himself65 requested changes

2023-02-04 21:18 UTC, Himself65 commented on packages/blocks/src/database-block/components/column-type/rich-text.ts
> +      (event.key === 'b' || event.key === 'B')
Refactor using a jump table?

2023-02-04 21:18 UTC, Himself65 commented on packages/blocks/src/database-block/components/column-type/rich-text.ts
> +  private _handleKeyDown(event: KeyboardEvent) {
```suggestion
  private _handleKeyDown = (event: KeyboardEvent) => {
```

2023-02-04 21:18 UTC, Himself65 commented on packages/blocks/src/database-block/components/column-type/rich-text.ts
> +        onKeyDown: this._handleKeyDown.bind(this),
```suggestion
        onKeyDown: this._handleKeyDown,
```

2023-02-04 21:18 UTC, Himself65 commented on packages/blocks/src/database-block/components/column-type/rich-text.ts
> +        onKeyDown: this._handleKeyDown.bind(this),
```suggestion
        onKeyDown: this._handleKeyDown,
```

2023-02-05 06:31 UTC, Himself65 approved these changes

2023-02-05 06:31 UTC, merged